##### LISTAS, VETORES, TUPLAS, DICIONÁRIOS E ESTRUTURAS COMPOSTAS

##### Lista

In [56]:
vendas = [1200, 1800, 1500, 2300]

print(vendas)

[1200, 1800, 1500, 2300]

In [16]:
vendas[3]

2300

In [17]:
vendas[-2]

1500

In [18]:
vendas[0] = 2000

print(vendas)

[2000, 1800, 1500, 2300]

In [20]:
print(vendas[0], vendas[2])

2000 1500

In [ ]:
# adicionar
vendas.append(2500)

print(vendas)

[2000, 1800, 1500, 2300, 2500]

In [29]:
# adicionar em posição específica: insert()

vendas.insert(1, 5000)

print(vendas)

[1200, 5000, 1800, 1500, 2300]

In [30]:
# adicionar vários elementos extend():

novos_elementos = [40, 50, 60]

vendas.extend(novos_elementos)

vendas

[1200, 5000, 1800, 1500, 2300, 40, 50, 60]

In [31]:
# Remover um elemento pelo o index pop():

vendas.pop(1)

vendas

[1200, 1800, 1500, 2300, 40, 50, 60]

In [36]:
# Ordenar uma lista, função sort()

vendas.sort(reverse = True)

vendas

[2300, 1800, 1500, 1200, 60, 50, 40]

In [ ]:
# Fatiamento
vendas

vendas[1:3]

[2300, 1800, 1500, 1200, 60, 50, 40]

In [41]:
vendas[3:6]

[1200, 60, 50]

In [44]:
vendas

vendas[:5]

[2300, 1800, 1500, 1200, 60]

In [46]:
vendas
vendas[2:]

[1500, 1200, 60, 50, 40]

In [47]:
# Remover remove()

vendas.remove(40)

vendas

[2300, 1800, 1500, 1200, 60, 50]

In [48]:
# quantidade de elementos numa lista len():

len(vendas)

6

In [49]:
# Maior valor

max(vendas)

2300

In [ ]:
# Menor valor

min(vendas)

50

In [51]:
# somar valores

sum(vendas)

6910

In [62]:
vendas_ajustadas = []
comissao = []

for venda in vendas:
       venda_ajustada = round(venda * 1.1, 2)
       vendas_ajustadas.append(venda_ajustada)
       comissao.append(venda * 0.1)

print(vendas_ajustadas)
print(comissao)

[1320.0, 1980.0, 1650.0, 2530.0]
[120.0, 180.0, 150.0, 230.0]

In [59]:
vendas

[1200, 1800, 1500, 2300]

### Tuplas

In [4]:
coordenadas = (-7.12, -34.86)

coordenadas

(-7.12, -34.86)

In [7]:
coordenadas[1]

-34.86

In [8]:
preco = [100, 200]

In [10]:
preco[0] = 150

In [13]:
coordenadas[1] = -8

TypeError: 'tuple' object does not support item assignment

In [15]:
preco.append(300)

print(preco)

[150, 200, 300]

In [16]:
coordenadas.append(-9)

AttributeError: 'tuple' object has no attribute 'append'

In [5]:
for coordenada in coordenadas:
       print(coordenada)

-7.12
-34.86

#### VETOR

In [ ]:
import numpy as np

vendas = np.array([1000, 1500, 1200, 1800, 2000])

[1000 1500 1200 1800 2000]
[100, 200]

In [ ]:

print(vendas)

In [ ]:

print(preco)

In [7]:
print(type(vendas))

<class 'numpy.ndarray'>

In [9]:
print(type(preco))

<class 'list'>

In [13]:
preco = [1000, 1500, 1200, 1800, 2000]

preco * 2

[1000, 1500, 1200, 1800, 2000, 1000, 1500, 1200, 1800, 2000]

In [17]:
quantidades = np.array([2, 3, 5, 1, 4])

print(quantidades)

print(vendas)

[2 3 5 1 4]
[1000 1500 1200 1800 2000]

In [16]:
faturamento = vendas * quantidades

faturamento

array([2000, 4500, 6000, 1800, 8000])

In [19]:
lista_3 = [1, 3]

lista_3 * 2

[1, 3, 1, 3]

In [30]:
# propriedades

vendas = np.array([
       [100, 200, 300],
       [150, 250, 350]       
       ]) 
vendas

array([[100, 200, 300],
       [150, 250, 350]])

In [31]:
# quantas dimensoes?

vendas.ndim

2

In [32]:
# qual o formato?

# 2 linhas
# 3 colunas

vendas.shape

(2, 3)

In [33]:
# quantos elementos?

vendas.size

6

In [34]:
exames = np.array([1200, 1300, 500])

exames

array([1200, 1300,  500])

In [35]:
exames.sum()

np.int64(3000)

In [36]:
exames.mean()

np.float64(1000.0)

In [37]:
for exame in exames:
       print(exame)

1200
1300
500

#### DICIONÁRIOS

In [51]:
produtos = {
       "nome":"Notebook",
       "preco": 3500,
       "estoque": 8
       }

produtos

{'nome': 'Notebook', 'preco': 3500, 'estoque': 8}

In [44]:
produtos["preco"]

3500

In [ ]:
# forma mais segura de obetr um valor
produtos.get("estoque")

8

In [47]:
# modificar

produtos["preco"] = 3200

produtos

{'nome': 'Notebook', 'preco': 3200, 'estoque': 8}

In [48]:
# adicionar

produtos["categoria"] = "Informatica"

produtos

{'nome': 'Notebook', 'preco': 3200, 'estoque': 8, 'categoria': 'Informatica'}

In [49]:
# remover elementos com del

del produtos["categoria"]

produtos

{'nome': 'Notebook', 'preco': 3200, 'estoque': 8}

In [ ]:
# limpar todos os elementos

produtos.clear()

produtos

{}

In [ ]:
# ver as chaves

produtos.keys()

dict_keys(['nome', 'preco', 'estoque'])

In [54]:
# ver valores

produtos.values()

dict_values(['Notebook', 3500, 8])

In [55]:
# lista dentro de um dicionário

produtos = {
       "nome":"Notebook",
       "preco": 3500,
       "cores": ["preto", "prata", "cinza"]       
}

produtos

{'nome': 'Notebook', 'preco': 3500, 'cores': ['preto', 'prata', 'cinza']}

In [56]:
produtos["cores"]

['preto', 'prata', 'cinza']

In [ ]:
# for com dicionarios

for chave in produtos:
       print(chave)

nome
preco
cores

In [58]:
produtos

{'nome': 'Notebook', 'preco': 3500, 'cores': ['preto', 'prata', 'cinza']}

In [59]:
# forma muito comum de percorrer dicionários: items()

for chave, valor in produtos.items():
       print(chave, valor)

nome Notebook
preco 3500
cores ['preto', 'prata', 'cinza']

#### ESTRUTURAS COMPOSTAS

In [60]:
# lista de dicionários

produtos = [
       {
              "produto":"Notebook",
              "preco": 3500,
              "estoque": 8
       },
       {
              "produto":"Mouse",
              "preco": 120,
              "estoque": 30
       },
       {
              "produto":"Monitor",
              "preco": 900,
              "estoque": 12
       }

       ]
produtos

[{'produto': 'Notebook', 'preco': 3500, 'estoque': 8},
 {'produto': 'Mouse', 'preco': 120, 'estoque': 30},
 {'produto': 'Monitor', 'preco': 900, 'estoque': 12}]

In [61]:
for produto in produtos:
       print(produto["produto"])

Notebook
Mouse
Monitor

In [62]:
for produto in produtos:
       print(produto["produto"], produto["preco"])

Notebook 3500
Mouse 120
Monitor 900

In [64]:
# dicionário com listas

vendas = {

       "produto":["Notebok", "Mouse", "Monitor"],
       "preco": [3500, 120, 900],
       "quantidade": [2, 10, 5]
}

vendas

{'produto': ['Notebok', 'Mouse', 'Monitor'],
 'preco': [3500, 120, 900],
 'quantidade': [2, 10, 5]}

In [65]:
import pandas as pd

df = pd.DataFrame(vendas)

df

   produto  preco  quantidade
0  Notebok   3500           2
1    Mouse    120          10
2  Monitor    900           5

In [67]:
receita = []

for preco, quantidade in zip(df["preco"], df["quantidade"]):
       receita.append(preco * quantidade)

In [69]:
df["receita"] = receita

df

   produto  preco  quantidade  receita
0  Notebok   3500           2     7000
1    Mouse    120          10     1200
2  Monitor    900           5     4500